Fix create volume from snapshot
Create volume from snapshot is currently broken and raises an exception
when we try to do it:

    new_vol = snap.create_volume()
  File "/home/geguileo/code/cinderlib/cinderlib/cinderlib.py", line 787, in create_volume
    new_vol = Volume(self.volume, **new_vol_params)
  File "/home/geguileo/code/cinderlib/cinderlib/cinderlib.py", line 401, in __init__
    self._populate_data()
  File "/home/geguileo/code/cinderlib/cinderlib/cinderlib.py", line 434, in _populate_data
    del old_snapshots[snap.id]
KeyError: '4067760f-4f56-43ba-8ad4-1cf0116d4b2b'

The cause is that we missed a comma in the tupple instantiation for
which fields to skip when using a Volume as the source for the fields of
another Volume, which made two of it's string entries form a single
string and thus not making us skip the "snapshots" field on the OVO.

This patch fixes this issue.