dosc: Fix object's dumps being called as method
In some of the documentation examples the `dumps` property is mistakenly
called as if it were an method, which will result in an error when
executed:

  TypeError: 'str' object is not callable

Fix these issues and be more explicit about this difference between the
library level method and the object's properties.