Fix DBError on attach on non Pike versions
If we use a Cinder release newer than Pike and the DB memory persistence
plugin, attaching fails with a DB error saying:

  oslo_db.exception.DBError: (sqlite3.InterfaceError) Error binding
  parameter 14 - probably unsupported type ...

This is caused by the new 'connector' field we are saving in the
database and needs to be converted from a dict to a string before being
saved.

This patch ensure the DB persistence plugins calls
`_convert_connector_to_db_format` before saving the object in the DB.