Fix loading object without configured backend
On commit fe9922d21c8a202f11a427a7b434820687db3ceb we added the
possibility of loading objects without configured backend, but there
were still some cases were loading could fail like this:

Traceback (most recent call last):
  File "/csi/cinderlib_csi/cinderlib_csi.py", line 127, in dolog
    result = f(self, request, context)
  File "/csi/cinderlib_csi/cinderlib_csi.py", line 168, in checker
    return f(self, request, context)
  File "/csi/cinderlib_csi/cinderlib_csi.py", line 210, in wrapper
    return func(self, request, context)
  File "/csi/cinderlib_csi/cinderlib_csi.py", line 839, in NodeStageVolume
    vol = self._get_vol(request.volume_id)
  File "/csi/cinderlib_csi/cinderlib_csi.py", line 360, in _get_vol
    volume_id=volume_id, backend_name=backend_name, **filters)
  File "/csi/cinderlib_csi/cl_crd.py", line 378, in get_volumes
    backend_name=backend_name)
  File "/csi/cinderlib_csi/cl_crd.py", line 169, in get
    resource = cinderlib.load(resource_json)
  File "/cinderlib/cinderlib/serialization.py", line 160, in load
    return getattr(objects, json_src['class']).load(json_src, save)
  File "/cinderlib/cinderlib/objects.py", line 195, in load
    backend = cls.backend_class.load_backend(json_src['backend'])
  File "/cinderlib/cinderlib/cinderlib.py", line 261, in load_backend
    raise Exception('Backend not present in system or json.')
Exception: Backend not present in system or json.

This patch fixes this issue by checking the `fail_on_missing_backend`
configuration option when loading using the base object class.

Also fixes saving of an object that has been loaded without the backend
configured in the system.